# Generated by Django 5.0.3 on 2024-03-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productimage_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                editable=False,
                related_name="product_images",
                to="products.productimage",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="photos/"),
        ),
    ]
